print('Hello World')
print('010','4692','9542',sep='-')
print('harchoio','amazon.com',sep='@')
print('2012','102','808', sep='|')
print('Welcome to',end='@')
print ('IT News',end='      ')
print()
print('hello')

#d = 정수, s= 문자열, f=실수 / %(자릿수)s % 대체 / {:>자릿수}.format 
print('%s %s' % ('one','two'))
print('{} {}'.format('one','two'))
print('{1} {0}'.format('one','two'))
print('%10s' % 'nice')
print('%5s' % ('nice'))
print('{:>10}'.format('nice'))
print('{:_>10}'.format('nice'))
print('%-10s' % ('nice'))
print('{:->10}'.format('nice'))
print('%5s' % 'Pythonstudy')
print('%.5s' % 'Pythonstudy')
print('{:10.5}'.format('Pythonstudy'))
print('%02.8f' % (3.14578643454))